name: kern-ux/sitemap
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: KernUx/Heading
    type: Basic
  - identifier: startPage
    type: Relation
    allowed: pages
    maxitems: 1
  - identifier: KernUx/Spacing
    type: Basic
