name: kern-ux/progress
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: label
    type: Text
    required: true
    max: 255
  - identifier: value
    type: Number
    default: 1
  - identifier: max
    type: Number
    default: 5
  - identifier: KernUx/Spacing
    type: Basic
