name: kern-ux/downloads
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: KernUx/Heading
    type: Basic
  - identifier: files
    type: File
    minitems: 1
  - identifier: KernUx/Spacing
    type: Basic
