name: kern-ux/card-grid
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: KernUx/Heading
    type: Basic
  - identifier: columns
    type: SelectNumber
    default: 3
    items:
      - label: '2'
        value: 2
      - label: '3'
        value: 3
      - label: '4'
        value: 4
  - identifier: cards
    type: Collection
    labelField: title
    fields:
      - identifier: title
        type: Text
        required: true
        max: 255
      - identifier: preline
        type: Text
        max: 255
      - identifier: text
        type: Textarea
        rows: 4
      - identifier: link
        type: Link
      - identifier: image
        type: File
        maxitems: 1
        allowed: common-image-types
  - identifier: KernUx/Spacing
    type: Basic
