name: kern-ux/heading
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: KernUx/Heading
    type: Basic
  - identifier: preline
    type: Text
    max: 255
  - identifier: subline
    type: Text
    max: 255
  - identifier: KernUx/Spacing
    type: Basic
