name: kern-ux/image
group: kern
vendorPrefix: tx_kernux
basics:
  - KernUx/Heading
  - KernUx/Spacing
fields:
  - identifier: image
    type: File
    minitems: 1
    maxitems: 1
    allowed: common-image-types
  - identifier: caption
    type: Text
    max: 500
  - identifier: aboveTheFold
    type: Checkbox
    default: 0
