<?php

declare(strict_types=1);

namespace BalatD\KernUx\Tests\Functional\Configuration;

use PHPUnit\Framework\Attributes\Test;
use TYPO3\TestingFramework\Core\Functional\FunctionalTestCase;

/**
 * Every content element an editor can still place has to render something.
 *
 * This extension replaces fluid_styled_content, and TYPO3 registers the classic content
 * types - textpic, uploads, shortcut, the whole menu_* family - in EXT:frontend itself
 * rather than in FSC. So on a KERN site those CTypes exist in the wizard whether or not
 * FSC is installed, while the TypoScript that renders them does not. The result is the
 * worst kind of defect this codebase can produce: an editor places an element, saves,
 * and the page region is empty. No exception, no log entry, nothing in the backend that
 * looks wrong.
 *
 * Fixing the twelve elements that were affected is not what keeps this closed - the next
 * core release adds a thirteenth. So this test derives the question from TCA instead of
 * restating an answer: whatever the wizard offers must be reachable, or be named here
 * with a reason.
 *
 * Deliberately not a rendering test. Rendering a menu needs a frontend request, a page
 * tree and a site, and none of that would make the failure clearer - a missing
 * `tt_content.<CType>` object is exactly the defect, and it is visible without booting a
 * frontend.
 */
final class CoreContentTypeRenderingTest extends FunctionalTestCase
{
    private const EXT_ROOT = __DIR__ . '/../../..';

    /**
     * CTypes that render through somebody else's TypoScript, and why.
     *
     * Both reach `lib.contentElement`, which this extension defines - they just do not
     * get their own object in our setup.typoscript, because Extbase's configurePlugin()
     * already emits one.
     *
     * @var array<string, string>
     */
    private const RENDERED_ELSEWHERE = [
        'list' => 'The plugin container. Extbase generates tt_content.<signature> per plugin.',
        'form_formframework' => 'The ext:form plugin, generated by ext:form itself.',
    ];
    protected array $coreExtensionsToLoad = ['form'];

    protected array $testExtensionsToLoad = [
        'friendsoftypo3/content-blocks',
        'balatd/kern-ux',
    ];

    #[Test]
    public function everyContentTypeTheWizardOffersHasSomethingThatRendersIt(): void
    {
        $setup = (string)file_get_contents(self::EXT_ROOT . '/Configuration/Sets/KernUx/setup.typoscript');

        $unrenderable = [];
        foreach (self::offeredContentTypes() as $cType => $group) {
            if (isset(self::RENDERED_ELSEWHERE[$cType])) {
                continue;
            }
            // Content Blocks generates tt_content.<CType> for every block it ships. They
            // are recognised by the item group this extension registers for them in
            // TCA/Overrides/tt_content.php - not by their CType spelling, which Content
            // Blocks derives differently in its 1.x and 2.x lines.
            if ($group === 'kern') {
                continue;
            }
            if (!str_contains($setup, 'tt_content.' . $cType)) {
                $unrenderable[] = $cType;
            }
        }

        self::assertSame(
            [],
            $unrenderable,
            'These content types are offered in the new-content-element wizard and nothing '
            . "renders them, so an editor gets an empty region with no error:\n  "
            . implode("\n  ", $unrenderable)
            . "\n\nEither add a tt_content.<CType> object to the site set's setup.typoscript, "
            . 'or take the type out of PageTsConfig/HideCoreContentElements.tsconfig with a '
            . 'comment saying why it cannot be rendered.',
        );
    }

    #[Test]
    public function nothingIsHiddenFromTheWizardThatNoLongerExists(): void
    {
        $known = [];
        foreach (self::cTypeItems() as $item) {
            $known[$item['value']] = true;
        }

        $stale = [];
        foreach (self::removedPerGroup() as $group => $cTypes) {
            foreach ($cTypes as $cType) {
                if (!isset($known[$cType])) {
                    $stale[] = $group . '.removeItems: ' . $cType;
                }
            }
        }

        self::assertSame(
            [],
            $stale,
            'HideCoreContentElements.tsconfig hides content types that no longer exist. A '
            . 'removeItems entry for an unknown type is silently ignored, so a type core has '
            . "renamed would quietly reappear in the wizard:\n  " . implode("\n  ", $stale),
        );
    }

    /**
     * The CTypes a wizard actually shows: everything in TCA, minus what the page TSconfig
     * removes from that item's own group.
     *
     * Per group on purpose. removeItems only applies to the group the item is in, so a
     * type listed under the wrong group is not hidden at all - which is exactly the kind
     * of mistake this test should not paper over.
     *
     * @return array<string, string> CType => wizard group
     */
    private static function offeredContentTypes(): array
    {
        $removed = self::removedPerGroup();

        $offered = [];
        foreach (self::cTypeItems() as $item) {
            if (in_array($item['value'], $removed[$item['group']] ?? [], true)) {
                continue;
            }
            $offered[$item['value']] = $item['group'];
        }

        return $offered;
    }

    /**
     * The CType select items, narrowed on the way out of the superglobal.
     *
     * $GLOBALS['TCA'] is mixed all the way down, and a wrong assumption about its shape
     * would make this test pass by finding nothing rather than by proving something - so
     * every level is checked and an empty result is a failure, not a pass.
     *
     * @return list<array{value: string, group: string}>
     */
    private static function cTypeItems(): array
    {
        $items = self::at($GLOBALS['TCA'] ?? null, ['tt_content', 'columns', 'CType', 'config', 'items']);
        self::assertIsArray($items, 'No CType items in TCA, so this test proves nothing.');
        self::assertNotSame([], $items, 'No CType items in TCA, so this test proves nothing.');

        $result = [];
        foreach ($items as $item) {
            if (!is_array($item) || !isset($item['value']) || !is_scalar($item['value'])) {
                continue;
            }
            $value = (string)$item['value'];
            // Divider items carry no CType of their own.
            if ($value === '' || str_starts_with($value, '--')) {
                continue;
            }
            $group = $item['group'] ?? 'default';
            $result[] = [
                'value' => $value,
                'group' => is_string($group) && $group !== '' ? $group : 'default',
            ];
        }

        return $result;
    }

    /**
     * Walks a key path through nested arrays, returning null the moment it does not hold.
     *
     * $GLOBALS['TCA'] is mixed all the way down and there is no shape to assert against,
     * so the alternative is a stack of is_array() guards that hides what is being read.
     *
     * @param list<string> $path
     */
    private static function at(mixed $value, array $path): mixed
    {
        foreach ($path as $key) {
            if (!is_array($value) || !array_key_exists($key, $value)) {
                return null;
            }
            $value = $value[$key];
        }

        return $value;
    }

    /**
     * The removeItems lists from the page TSconfig, keyed by wizard group.
     *
     * @return array<string, list<string>>
     */
    private static function removedPerGroup(): array
    {
        $file = self::EXT_ROOT . '/Configuration/Sets/KernUx/PageTsConfig/HideCoreContentElements.tsconfig';
        $contents = (string)file_get_contents($file);

        $matched = preg_match_all(
            '/^\s*(\w+)\.removeItems\s*:?=\s*(?:addToList\()?([^)\r\n]+)\)?\s*$/m',
            $contents,
            $matches,
            PREG_SET_ORDER,
        );
        if ($matched === false || $matched === 0) {
            self::fail("No removeItems lines in {$file}, so the wizard is not restricted at all.");
        }

        $removed = [];
        foreach ($matches as $match) {
            foreach (explode(',', $match[2]) as $cType) {
                $cType = trim($cType);
                if ($cType !== '') {
                    $removed[$match[1]][] = $cType;
                }
            }
        }

        return $removed;
    }
}
