name: kern-ux/gallery
group: kern
vendorPrefix: tx_kernux
fields:
  - identifier: KernUx/Heading
    type: Basic
  - identifier: images
    type: File
    minitems: 1
    allowed: common-image-types
  - identifier: columns
    type: SelectNumber
    default: 3
    items:
      - label: '2'
        value: 2
      - label: '3'
        value: 3
      - label: '4'
        value: 4
  - identifier: KernUx/Spacing
    type: Basic
