name: kern-ux/text
group: kern
vendorPrefix: tx_kernux
basics:
  - KernUx/Heading
  - KernUx/Spacing
fields:
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
    richtextConfiguration: kern_ux
